name: CI Build

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Cache Gradle project-local state
        uses: actions/cache@v4
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle-project-${{ github.ref }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', 'src/main/resources/hbm_at.cfg') }}
          restore-keys: |
            ${{ runner.os }}-gradle-project-${{ github.ref }}-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/
